version: '3.9'

services:
  apidock:
    build: ./apidock
    ports:
      - "4000:4000"
    volumes:
      - ./apidock:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - docknet

  frontdock:
    build: ./frontdock
    ports:
      - "3000:3000"
    volumes:
      - ./frontdock:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - USE_POLLING=true
      - FAST_REFRESH=false # Desactiva Fast Refresh (a veces falla en Docker)
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    networks:
      - docknet

networks:
  docknet:
    driver: bridge
