apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontdock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontdock
  template:
    metadata:
      labels:
        app: frontdock
    spec:
      containers:
        - name: frontdock
          image: us-east5-docker.pkg.dev/skilled-duality-441619-j5/protectodockergcloud/container_frontdock
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://34.162.173.119:4000"
